import React, { useState } from 'react';
import { ResizableCriteriaWindow, WindowState } from '../../ui/ResizableCriteriaWindow';
import { ChevronDown, ArrowUpRight, ArrowUp, ArrowDown } from 'lucide-react';

interface ApprovalTemplatesWindowProps {
  windowState: WindowState;
  onClose: () => void;
  onUpdateState: (s: Partial<WindowState>) => void;
  onFocus: () => void;
}

const sapLabelStyle = "text-[11px] text-[#333] whitespace-nowrap leading-[18px]";
const sapInputStyle = "h-[18px] border border-gray-400 px-1 text-[11px] outline-none focus:border-orange-400 bg-white w-full";
const sapButtonStyle = "px-3 h-[20px] bg-gradient-to-b from-[#fff6d5] via-[#ffec99] to-[#ffd700]/60 border border-gray-500 text-[11px] font-bold shadow-sm rounded-[1px] min-w-[70px] hover:brightness-95 active:shadow-inner flex items-center justify-center";
const sapGreyButtonStyle = "px-3 h-[20px] bg-gradient-to-b from-[#fefefe] to-[#d1d1d1] border border-gray-500 text-[11px] shadow-sm rounded-[1px] min-w-[70px] hover:brightness-95 active:shadow-inner flex items-center justify-center";

export const ApprovalTemplatesWindow: React.FC<ApprovalTemplatesWindowProps> = ({
  windowState,
  onClose,
  onUpdateState,
  onFocus
}) => {
  const [activeTab, setActiveTab] = useState<'Originator' | 'Documents' | 'Stages' | 'Terms'>('Originator');

  const salesDocs = ['Sales Quotation', 'Sales Order', 'Delivery', 'Returns Request', 'Returns', 'A/R Down Payment', 'A/R Invoice', 'A/R Credit Memo'];
  const purchaseDocs = ['Purchase Quotation', 'Purchase Order', 'Goods Receipt PO', 'Goods Returns Request', 'Goods Returns', 'A/P Down Payment', 'A/P Invoice', 'A/P Credit Memo', 'Internal Requisition', 'Purchase Request'];
  const inventoryDocs = ['Goods Receipt', 'Goods Issue', 'Inventory Transfer Request', 'Inventory Transfer', 'Inventory Opening Balance'];
  const blanketDocs = ['Sales Blanket Agreements', 'Purchase Blanket Agreements'];
  const countingDocs = ['Inventory Counting', 'Inventory Posting'];

  return (
    <ResizableCriteriaWindow
      title="Approval Templates - Setup"
      windowState={windowState}
      onClose={onClose}
      onUpdateState={onUpdateState}
      onFocus={onFocus}
      minWidth={850}
      minHeight={650}
    >
      <div className="flex-1 p-3 flex flex-col gap-4 bg-[#f0f0f0] overflow-hidden">
        
        {/* Header Configuration */}
        <div className="flex flex-col gap-1">
           <div className="grid grid-cols-[100px_250px] gap-x-2 items-center">
              <span className={sapLabelStyle}>Name</span>
              <input type="text" className={`${sapInputStyle} !bg-[#fffbd0]`} />
              
              <span className={sapLabelStyle}>Description</span>
              <input type="text" className={sapInputStyle} />
           </div>
           <div className="flex flex-col mt-1">
              <label className="flex items-center gap-2 cursor-pointer">
                 <input type="checkbox" defaultChecked className="w-3.5 h-3.5" />
                 <span className={sapLabelStyle}>Active</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer ml-4">
                 <input type="checkbox" defaultChecked className="w-3.5 h-3.5" />
                 <span className={sapLabelStyle}>Active When Updating Documents Not Generated by Approval Process</span>
              </label>
           </div>
        </div>

        {/* Tabs Container */}
        <div className="flex-1 flex flex-col border border-gray-400 bg-white shadow-inner overflow-hidden">
           {/* Tab Bar */}
           <div className="flex bg-[#f0f0f0] border-b border-gray-400 px-4">
              {['Originator', 'Documents', 'Stages', 'Terms'].map(tab => (
                <button 
                  key={tab}
                  onClick={() => setActiveTab(tab as any)}
                  className={`px-6 h-[22px] text-[11px] border border-gray-400 border-b-0 rounded-t-[3px] -ml-[1px] transition-colors ${activeTab === tab ? 'bg-white font-bold -mb-[1px] z-10' : 'bg-[#e4e4e4] hover:bg-gray-200'}`}
                >
                  {tab}
                </button>
              ))}
           </div>

           {/* Tab Content */}
           <div className="flex-1 p-3 overflow-hidden flex flex-col">
              {activeTab === 'Originator' && (
                <div className="flex-1 flex flex-col">
                   <h3 className="text-[11px] font-bold underline mb-2">Originator</h3>
                   <div className="flex-1 border border-gray-300 overflow-auto custom-scrollbar">
                      <table className="w-full border-collapse text-[11px]">
                         <thead className="sticky top-0 bg-[#f8f8f8] border-b border-gray-300 z-10">
                            <tr className="h-[22px]">
                               <th className="w-8 border-r border-gray-300 px-1 font-normal text-left text-gray-700 bg-gradient-to-b from-[#fefefe] to-[#dcdcdc]">#</th>
                               <th className="w-1/2 border-r border-gray-300 px-1 font-normal text-left text-gray-700 bg-gradient-to-b from-[#fefefe] to-[#dcdcdc]">User</th>
                               <th className="px-1 font-normal text-left text-gray-700 bg-gradient-to-b from-[#fefefe] to-[#dcdcdc] flex items-center justify-between">
                                  <span>Department</span>
                                  <ArrowUpRight className="w-3 h-3 text-blue-600 cursor-pointer" />
                               </th>
                            </tr>
                         </thead>
                         <tbody>
                            <tr className="h-[18px] border-b border-gray-100 bg-[#ffed99]/30">
                               <td className="w-8 border-r border-gray-100 text-center text-gray-500">1</td>
                               <td className="border-r border-gray-100 px-1 flex items-center justify-end">
                                  <ChevronDown className="w-3 h-3 text-gray-800" />
                               </td>
                               <td className="px-1"></td>
                            </tr>
                            {Array.from({ length: 20 }).map((_, i) => (
                              <tr key={i} className="h-[18px] border-b border-gray-50">
                                 <td className="w-8 border-r border-gray-100"></td>
                                 <td className="border-r border-gray-100"></td>
                                 <td></td>
                              </tr>
                            ))}
                         </tbody>
                      </table>
                   </div>
                </div>
              )}

              {activeTab === 'Documents' && (
                <div className="flex-1 overflow-auto custom-scrollbar">
                   <div className="flex items-center gap-2 mb-4">
                      <input type="radio" checked readOnly className="w-3.5 h-3.5" />
                      <span className={sapLabelStyle}>Documents</span>
                   </div>
                   <div className="grid grid-cols-2 gap-x-12 gap-y-6">
                      {/* Sales */}
                      <div className="space-y-1">
                         <h4 className="text-[11px] font-bold text-[#333] underline mb-1">Sales - A/R</h4>
                         {salesDocs.map(doc => (
                            <label key={doc} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50">
                               <input type="checkbox" className="w-3.5 h-3.5" />
                               <span className={sapLabelStyle}>{doc}</span>
                            </label>
                         ))}
                      </div>
                      {/* Purchasing */}
                      <div className="space-y-1">
                         <h4 className="text-[11px] font-bold text-[#333] underline mb-1">Purchasing - A/P</h4>
                         {purchaseDocs.map(doc => (
                            <label key={doc} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50">
                               <input type="checkbox" className="w-3.5 h-3.5" />
                               <span className={sapLabelStyle}>{doc}</span>
                            </label>
                         ))}
                      </div>
                      {/* Inventory */}
                      <div className="space-y-1">
                         <h4 className="text-[11px] font-bold text-[#333] underline mb-1">Inventory</h4>
                         {inventoryDocs.map(doc => (
                            <label key={doc} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50">
                               <input type="checkbox" className="w-3.5 h-3.5" />
                               <span className={sapLabelStyle}>{doc}</span>
                            </label>
                         ))}
                      </div>
                      {/* Payment */}
                      <div className="space-y-1">
                         <h4 className="text-[11px] font-bold text-[#333] underline mb-1">Payment</h4>
                         <label className="flex items-center gap-2 cursor-pointer hover:bg-gray-50">
                            <input type="checkbox" className="w-3.5 h-3.5" />
                            <span className={sapLabelStyle}>Outgoing Payment</span>
                         </label>
                      </div>
                      {/* Blanket */}
                      <div className="space-y-1">
                         <h4 className="text-[11px] font-bold text-[#333] underline mb-1">Blanket Agreement</h4>
                         {blanketDocs.map(doc => (
                            <label key={doc} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50">
                               <input type="checkbox" className="w-3.5 h-3.5" />
                               <span className={sapLabelStyle}>{doc}</span>
                            </label>
                         ))}
                      </div>
                      {/* Counting */}
                      <div className="space-y-1">
                         <h4 className="text-[11px] font-bold text-[#333] underline mb-1">Inventory Counting Transactions</h4>
                         {countingDocs.map(doc => (
                            <label key={doc} className="flex items-center gap-2 cursor-pointer hover:bg-gray-50">
                               <input type="checkbox" className="w-3.5 h-3.5" />
                               <span className={sapLabelStyle}>{doc}</span>
                            </label>
                         ))}
                      </div>
                   </div>
                </div>
              )}

              {activeTab === 'Stages' && (
                <div className="flex-1 flex gap-2">
                   <div className="flex-1 flex flex-col">
                      <h3 className="text-[11px] font-bold underline mb-2">Approval Stages</h3>
                      <div className="flex-1 border border-gray-300 overflow-auto custom-scrollbar">
                         <table className="w-full border-collapse text-[11px]">
                            <thead className="sticky top-0 bg-[#f8f8f8] border-b border-gray-300 z-10">
                               <tr className="h-[22px]">
                                  <th className="w-8 border-r border-gray-300 px-1 font-normal text-left text-gray-700 bg-gradient-to-b from-[#fefefe] to-[#dcdcdc]">#</th>
                                  <th className="w-1/2 border-r border-gray-300 px-1 font-normal text-left text-gray-700 bg-gradient-to-b from-[#fefefe] to-[#dcdcdc]">Stage Name</th>
                                  <th className="px-1 font-normal text-left text-gray-700 bg-gradient-to-b from-[#fefefe] to-[#dcdcdc] flex items-center justify-between">
                                     <span>Stage Description</span>
                                     <ArrowUpRight className="w-3 h-3 text-blue-600 cursor-pointer" />
                                  </th>
                               </tr>
                            </thead>
                            <tbody>
                               <tr className="h-[18px] border-b border-gray-100 bg-[#ffed99]/30">
                                  <td className="w-8 border-r border-gray-100 text-center text-gray-500">1</td>
                                  <td className="border-r border-gray-100"></td>
                                  <td></td>
                               </tr>
                               {Array.from({ length: 25 }).map((_, i) => (
                                 <tr key={i} className="h-[18px] border-b border-gray-50">
                                    <td className="w-8 border-r border-gray-100"></td>
                                    <td className="border-r border-gray-100"></td>
                                    <td></td>
                                 </tr>
                               ))}
                            </tbody>
                         </table>
                      </div>
                   </div>
                   <div className="w-8 flex flex-col gap-2 pt-8">
                      <button className="w-6 h-6 border border-gray-400 bg-white flex items-center justify-center hover:bg-gray-100 shadow-sm"><ArrowUp className="w-3.5 h-3.5" /></button>
                      <button className="w-6 h-6 border border-gray-400 bg-white flex items-center justify-center hover:bg-gray-100 shadow-sm"><ArrowDown className="w-3.5 h-3.5" /></button>
                   </div>
                </div>
              )}

              {activeTab === 'Terms' && (
                <div className="flex flex-col gap-4">
                   <div className="flex flex-col gap-2">
                      <h3 className="text-[11px] font-bold underline">Launch Approval Process:</h3>
                      <label className="flex items-center gap-2 cursor-pointer ml-4">
                         <input type="radio" name="launch" defaultChecked className="w-3.5 h-3.5" />
                         <span className={sapLabelStyle}>Always</span>
                      </label>
                      <label className="flex items-center gap-2 cursor-pointer ml-4">
                         <input type="radio" name="launch" className="w-3.5 h-3.5" />
                         <span className={sapLabelStyle}>When the Following Applies</span>
                      </label>
                   </div>
                </div>
              )}
           </div>
        </div>

        {/* Footer */}
        <div className="flex gap-2">
           <button className={sapButtonStyle}>Add</button>
           <button onClick={onClose} className={sapButtonStyle}>Cancel</button>
        </div>

      </div>
    </ResizableCriteriaWindow>
  );
};
